name: CD React App
on: push
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Testing project
        run: npm run test
  lint:
    runs-on: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint project
        run: npm run lint
  build:
    runs-on: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: CD workflow
        run: echo Finished