name: CD React App
on: push
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Testing project
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint project
        run: npm run lint
  build:
    runs-on: windows-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          path: build
          name: build-files
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: build-files
